trackit/core/urls.py
from django.urls import path
from rest_framework import routers
from .api import UserViewSet, GroupViewSet, UserUpdateAPIView, UserProfileViewSet, ChangePasswordAPIView, RegisterViewSet, UserVerificationViewSet, UserListViewSet, VerifyUserViewSet, DeclineVerificationViewSet
from . import views


router = routers.DefaultRouter()
router.register('api/core/user', UserViewSet)
router.register('api/core/all/user', UserListViewSet)
router.register('api/core/group', GroupViewSet)
router.register('api/core/user-profile', UserProfileViewSet)
router.register('api/auth/registration', RegisterViewSet)
router.register('api/core/all/verification', UserVerificationViewSet)
router.register('api/core/verify/user', VerifyUserViewSet)
router.register('api/core/decline/user', DeclineVerificationViewSet)

urlpatterns = [
   path('', views.home, name='home'),
   path('registration/', views.register, name='register'),
   path('verification/', views.verification, name='verification'),
   path('core/group', views.group_list, name='group_list'),
   path('core/user', views.user_list, name='user_list'),
   path('core/user/<int:pk>/profile', views.user_profile, name='user_profile'),

   path('api/core/user/<int:pk>/change-password/', ChangePasswordAPIView.as_view(), name='change-password'),
   path('core/user/<int:pk>/update', UserUpdateAPIView.as_view(), name='user-update'),
]

urlpatterns += router.urls

trackit/requests/urls.py
from django.urls import path
from rest_framework import routers
from .api import (
   AttachmentViewSet, 
   CommentListCreateAPIView,
   CRUDEventList, 
   FormStatusOfficerViewSet,
   NotificationDeleteViewSet,
   NotificationViewSet, 
   RequestFormCRUDViewSet, 
   RequestFormStatusViewSet,
   RequestFormStatusDeleteViewSet, 
   RequestFormViewSet, 
   StatusOfficerViewset,
   TicketActionViewSet,
   TicketCounterViewSet, 
   TicketCRUDViewSet, 
   TicketDashboardViewSet,
   TicketGenerateReferenceViewSet,
   TicketProfileViewSet, 
   TicketStatusViewSet, 
   TicketViewSet, 
)
from . import views

router = routers.DefaultRouter()
router.register('api/requests/forms/crud', RequestFormCRUDViewSet, basename='RequestForm')
router.register('api/requests/forms/all', RequestFormViewSet, basename='RequestFormList')
router.register('api/requests/ticket/crud', TicketCRUDViewSet, basename='Ticket')
router.register('api/requests/ticket/all', TicketViewSet, basename='TicketList')
router.register('api/requests/ticket/counter', TicketCounterViewSet, basename='TicketCount')
router.register('api/requests/ticket/myrequests', TicketProfileViewSet, basename='TicketProfile')
router.register('api/requests/ticket/latest', TicketDashboardViewSet, basename='TicketDashboard')
router.register('api/requests/ticket/generate_reference', TicketGenerateReferenceViewSet, basename='TicketGenerateReference')
router.register('api/requests/ticket/status', TicketStatusViewSet, basename='TicketStatus')
router.register('api/requests/ticket/actions', TicketActionViewSet, basename='TicketAction')
router.register('api/requests/form/status', RequestFormStatusViewSet, basename='RequestFormStatus')
router.register('api/requests/form/delete/status', RequestFormStatusDeleteViewSet, basename='RequestFormStatusDelete')
router.register('api/requests/formstatus/officer', FormStatusOfficerViewSet, basename='FormStatusOfficer')
router.register('api/requests/attachments', AttachmentViewSet, basename='Attachment')
router.register('api/user/notifications', NotificationViewSet, basename='Notification')
router.register('api/status/officer', StatusOfficerViewset, basename='StatusOFficer')

urlpatterns = [
   path('requests/lists', views.ticket, name='ticket'),
   path('requests/new', views.create_ticket, name='create_ticket'),
   path('requests/<uuid:ticket_id>/detail', views.detail_ticket, name='detail_ticket'),
   path('requests/<uuid:ticket_id>/view', views.view_ticket, name='view_ticket'),
   path('requests/track', views.ticket_log_list, name='ticket_log_list'),

   path('api/ticket/logs/', CRUDEventList.as_view()), # easyaudit_crudevent api
   path('api/requests/comments/', CommentListCreateAPIView.as_view(), name='list-create-comment'), # list/create comment api
   path('api/user/notifications/delete/', NotificationDeleteViewSet.as_view({'delete' : 'destroy'})), # easyaudit_crudevent api
]

urlpatterns += router.urls

trackit/trackit/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

from core import views

urlpatterns = [
   path('admin/', admin.site.urls),
   path('accounts/', include('django.contrib.auth.urls')),
   path('api-auth/', include('rest_framework.urls')),

   path('', include('core.urls')),
   path('', include('config.urls')),
   path('', include('requests.urls')),
   path('', include('announcement.urls')),
   path('', include('events.urls')),
   path('', include('tasks.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  
handler403 = 'core.views.forbidden'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.unexpected_error'

trackit/requests/models.py
import uuid
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_mysql.models import JSONField
from django.contrib.auth.models import Group
from easyaudit.models import CRUDEvent
from config.models import Department, Category, Status, CategoryType
from core.models import User


def upload_file_url(instance, filename):
    ticket_no = str(instance.ticket.ticket_no)
    return "attachments/{0}/{1}/".format(ticket_no, filename) 

# Create your models here.
class RequestForm(models.Model):
    name =  models.CharField(max_length=255)
    prefix = models.CharField(max_length=5)
    color = models.CharField(max_length=50, blank=True)
    status = models.ManyToManyField(Status, related_name='forms', blank=True, through='RequestFormStatus')
    fields = JSONField()
    group = models.ManyToManyField(Group, related_name='groups', blank=True)
    category_types = models.ManyToManyField(CategoryType, related_name='form_types', blank=True)
    guide = models.CharField(max_length=255, blank=True)
    is_active = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

# Main Service Request Model
class Ticket(models.Model):
    ticket_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    ticket_no = models.CharField(max_length=25, blank=True)
    description = models.CharField(max_length=255)
    reference_no = models.CharField(max_length=15, blank=True)
    form_data = JSONField()
    
    request_form = models.ForeignKey(RequestForm, related_name='formtype_tickets', on_delete=models.PROTECT)
    category = models.ManyToManyField(Category, related_name='category_tickets', blank=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    requested_by = models.ForeignKey(User, related_name='user_tickets', on_delete=models.PROTECT)
    status = models.ForeignKey(Status, related_name='status_tickets', on_delete=models.SET_NULL, null=True, blank=True)

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        permissions = [
            ("generate_reference", "Can generate reference no"),
        ]

    def __str__(self):
        return str(self.ticket_id)

class RequestFormStatus(models.Model):
    form = models.ForeignKey(RequestForm, related_name="request_forms", on_delete=models.CASCADE)
    status = models.ForeignKey(Status, related_name='form_statuses', on_delete=models.CASCADE)
    officer = models.ManyToManyField(User, related_name='status_officers', blank=True)
    order = models.PositiveSmallIntegerField(null=True, blank=True)
    is_client_step =  models.BooleanField(default=False)
    is_head_step =  models.BooleanField(default=False)
    has_pass_fail = models.BooleanField(default=False)
    has_approving = models.BooleanField(default=False)
    has_event = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    
    @property
    def is_not_for_task(self):
        return not self.is_client_step and not self.is_head_step and not self.officer.exists()

class Attachment(models.Model):
    file = models.FileField(upload_to=upload_file_url)
    file_name = models.CharField(max_length=255, blank=True)
    file_type = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    ticket = models.ForeignKey(Ticket, related_name='attachments_ticket', on_delete=models.CASCADE)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    uploaded_by = models.ForeignKey('core.User', related_name='attachments_user', on_delete=models.CASCADE)

class Notification(models.Model):
    log = models.ForeignKey(CRUDEvent, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notifications')
    unread = models.BooleanField(default=True)

class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='all_comments')
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, related_name='comments')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.ticket, self.user.get_full_name())

trackit/templates/pages/requests/boards.html
{% extends '../../base.html' %}
{% load static %}

{% block title %} Requests {% endblock %}

{% block extrastyle %}

<link rel="stylesheet" href="{% static 'src/css/board.css' %}">
{% endblock %}

{% block content %}
<!-- Content Header -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h5 class="font-weight-bolder">Request Boards </h5>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right text-xs">
                    <li class="breadcrumb-item"><a href="{% url 'home' %}" class="text-orange"><i
                                class="fas fa-home"></i></a></li>
                    <li class="breadcrumb-item">Request</li>
                    <li class="breadcrumb-item active">Boards</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<!-- /.content -->
{% if request.user.is_superuser %}
<section class="content">
    <div class="container-fluid">
   
         <!-- Default box -->
         <div class="row">
            <div class="col-12 m-0">
               <div class="card bg-secondary mt-2 mb-2">
                  <div class="card-body p-0">
                     <div class="container-fluid">
                        <div class="row">
                           <div class="col-12 col-sm-4 p-1 ">
                            <select class="form-control form-control-sm w-100" id="select_form">
                                <option></option>
                                {% for form in forms %}
                                    <option value={{form.id}}>{{form.name}}</option>
                                {% endfor %}
                            </select>
                           </div>
                        </div>
                     </div>               
                  </div>
               </div>
            </div>
        </div>

        <!-- Boards Body-->
        <div class="board-wrapper">
            <div class="row-fluid mt-2">
                <p class="board-helper">*Select a form to show board cards</p>
            </div>
        </div>
    </div>
</section>
{% else %}
<section class="content">
    You don't have permission to view this page
</section>
{% endif %}
{% endblock %}


{% block extrascript %}
<!-- JQuery UI -->
<script type="text/javascript" src="{% static 'vendor/jquery-ui/js/jquery-ui.js' %}"></script>
<script type="text/javascript" src="{% static 'src/js/requests/boards.js' %}"></script>
{% endblock %}

trackit/templates/pages/requests/ticket_lists.html
{% extends '../../base.html' %}
{% load static %}

{% block title %} All Requests | {% endblock %}

{% block extrastyle %}
<link rel="stylesheet" href="{% static 'src/css/requests.css' %}">
{% endblock %}

{% block content %}
<!-- Content Header -->
<section class="content-header">
   <div class="container-fluid">
      <div class="row mb-2">
         <div class="col-sm-6">
            <h5 class="font-weight-bolder">All Requests </h5>
         </div>
         <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right text-xs">
               <li class="breadcrumb-item"><a href="{% url 'home' %}" class="text-orange"><i
                        class="fas fa-home"></i></a></li>
               <li class="breadcrumb-item">Request</li>
               <li class="breadcrumb-item">All Requests</li>
               <li class="breadcrumb-item active">List</li>
            </ol>
         </div>
      </div>
   </div>
</section>

<!-- /.content -->
<section class="content">
   <div class="container-fluid">
      <!-- Content Filters, Search and Create Section -->
      <div class="d-flex mb-1">
         <div class="dropdown dropdown-filter mr-2" id="intro_filter">
            <button class="btn btn-sm btn-light shadow-sm dropdown-filter-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <i class="fas fa-xs fa-filter m-0 d-inline d-md-none"></i>
               <span class="d-none d-md-inline pl-1">Filter <i class="fas fa-caret-down ml-1"></i></span>
            </button>
            <div class="dropdown-menu dropdown-menu-lg dropdown-filter-menu">
               <form id="form-filter">
                  <div class="p-3 scrollable-menu">
                     <div class="form-group mb-1">
                        <label for="requestform-filter">By Request Form</label>
                        <select class="form-control form-control-sm select-filter" id="requestform-filter" name="requestform-filter">
                           <option value="">All</option>
                           {% for form in forms %}
                           <option value={{form.id}}>{{form}}</option>
                           {% endfor %}
                        </select>
                     </div>
                     <div class="form-group mb-1">
                        <label for="type-filter">By Category Type</label>
                        <select class="form-control form-control-sm select-filter" id="type-filter" name="type-filter">
                           <option value="">All</option>
                           {% for type in types %}
                           <option value={{type.id}}>{{type}}</option>
                           {% endfor %}
                        </select>
                     </div>
                     <div class="form-group mb-1">
                        <label for="category-filter">By Category </label>
                        <select class="form-control form-control-sm select-filter" id="category-filter" name="category-filter">
                           <option value="">All</option>
                        </select>
                     </div>
                     <div class="form-group mb-1">
                        <label for="department-filter">By Department </label>
                        <select class="form-control form-control-sm select-filter" id="department-filter" name="department-filter">
                           <option value="">All</option>
                           {% for department in departments %}
                           <option value={{department.id}}>{{department}}</option>
                           {% endfor %}
                        </select>
                     </div>
                     <div class="form-group mb-1">
                        <label for="status-filter">By Status </label>
                        <select class="form-control form-control-sm select-filter" id="status-filter" name="status-filter">
                           <option value="">All</option>
                           {% for status in statuses %}
                           <option value={{status.id}}>{{status}}</option>
                           {% endfor %}
                        </select>
                     </div>
                     {% if user.is_superuser or user.is_staff %}
                     <div class="form-group mb-1">
                        <label for="active-filter">By Task Officer </label>
                        <select class="form-control form-control-sm select-filter" id="officer-filter" name="officer-filter">
                           <option value="">All</option>
                           {% for user in task_officers %}
                           <option value={{user.id}}>{{user}}</option>
                           {% endfor %}
                        </select>
                     </div>
                     {% endif %}
                     {% if user.is_superuser %}
                     <div class="form-group mb-1">
                        <label for="active-filter">By Active </label>
                        <select class="form-control form-control-sm select-filter" id="active-filter" name="active-filter">
                           <option value="">All</option>
                           <option value="0">Yes</option>
                           <option value="1">No</option>
                        </select>
                     </div>
                     {% endif %}
                     <div class="form-group mb-1">
                        <label for="date-filter">By Date Requested </label>
                        <input type="date" class="form-control form-control-sm mb-2" id="date-from-filter" name="date-filter" placeholder="From">
                        <input type="date" class="form-control form-control-sm" id="date-to-filter" name="date-filter" placeholder="To">
                     </div>
                  </div>
                  <div class="dropdown-divider"></div>
                  <div class="d-flex flex-row-reverse pt-2 pb-2 pl-3 pr-3">
                     <div><button class="btn btn-sm btn-orange ml-1" id="btn_apply"> <span>Apply</span> </button></div>
                     <div><a class="btn btn-sm btn-link text-secondary" id="btn_clear"> <span>Clear</span> </a></div>
                     <div class="mr-auto"><a class="btn btn-sm btn-link text-secondary pl-0" id="close_dropdown"> <span>Close</span> </a></div>
                  </div>
               </form>
            </div>
         </div>
         <div class="col-auto col-lg-3 p-0" id="intro_search"> 
            <div class="input-group shadow-sm">
               <input type="search" class="form-control form-control-sm" placeholder="Search" id="search-input">
               <div class="input-group-append">
                 <button class="btn btn-sm btn-outline-secondary" type="button" id="execute-search">
                     <i class="fas fa-sm fa-search"></i>
                  </button>
               </div>
            </div>
         </div>
         <div class="ml-auto" id="intro_addbutton">
            {% if perms.requests.add_ticket %}
            <a href="{% url 'create_ticket' %}" class="btn btn-xs btn-orange btn-new shadow-sm" id="btn-create-list"><i class="fas fa-xs fa-plus"></i> <span class="d-none d-sm-inline ml-1">Create Request</span></a>
            {% endif %}
         </div>
      </div>

      <!-- Table -->
      <div class="row">
         <div class="col-12 col-sm-12 m-0">
            <div class="card shadow-sm mt-2 mb-2">
               <div class="card-body p-0">
                  <template id="table_spinner">
                     <div class="d-flex justify-content-center align-items-center">
                        <div class="spinner-border text-orange mr-2" style="width: 1.2rem; height: 1.2rem;" role="status">
                        </div>
                        <span class="text-secondary">Fetching...</span>
                     </div>
                  </template>
                  <template id="table_gif">
                     <b class="text-orange">All requests</b> are displayed here. To view a request, click the ticket number.
                     <img src="{% static '/src/img/view_request_2.gif' %}" width="100%" class="border border-light mt-2">
                  </template>
                  <table id="dt_requests" class="table table-hover m-0" width="100%">
                     <thead id="intro_tablehead">
                        <tr>
                           <th data-priority="1">Ticket No</th>
                           <th data-priority="2">Request</th>
                           <th>Description</th>
                           <th>Category</th>
                           <th>Reference No</th>
                           <th data-priority="3">Requested By</th>
                           <th>Date Requested</th>
                           <th data-priority="4">Status</th>
                           <th>Officer</th>
                           <th>active</th>
                        </tr>
                     </thead>
                     <tbody id="intro_tbody"></tbody>
                  </table>
               </div>
            </div>
         </div>
      </div>
   </div>
   <input type="hidden" id="changeTicketHidden" value="{% if perms.requests.change_ticket %}true{% else %}false{% endif %}">
</section>
{% endblock %}

{% block extrascript %}
<script type="text/javascript" src="{% static 'src/js/requests/request.js' %}"></script>
{% endblock %}

trackit/templates/pages/requests/track.html
{% extends '../../base.html' %}
{% load static %}

{% block title %} Track Request | {% endblock %}

{% block extrastyle %}
{% endblock %}

{% block content %}
<!-- Content Header -->
<section class="content-header">
   <div class="container-fluid">
      <div class="row mb-2">
         <div class="col-sm-6">
            <h5 class="font-weight-bolder">Track Request</h5>
         </div>
         <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right text-xs">
               <li class="breadcrumb-item"><a href="{% url 'home' %}" class="text-orange"><i
                        class="fas fa-home"></i></a></li>
               <li class="breadcrumb-item">Tracking</li>
               <li class="breadcrumb-item active">List</li>
            </ol>
         </div>
      </div>
   </div>
</section>

<!-- /.content -->
<section class="content">
   <div class="container-fluid">

      <!-- Content Filters, Search and Create Section -->
      <div class="d-flex mb-1">
         <div class="col-auto col-lg-3 p-0"> 
            <div class="input-group shadow-sm">
               <input type="search" class="form-control form-control-sm" placeholder="Enter tracking number" id="search-input">
               <div class="input-group-append">
                 <button class="btn btn-sm btn-outline-secondary" type="button" id="execute-search">
                     <i class="fas fa-sm fa-search"></i>
                  </button>
               </div>
            </div>
         </div>
      </div>
      
      <div class="row">
         <!-- Datatable -->
         <div class="col-md col-sm-12">
            <div class="card shadow-sm mt-2 mb-2">
               <div class="card-body p-0">
                  <table id="dt_tracking" class="table table-hover" width="100%">
                     <thead>
                        <tr>
                           <th>Date</th>
                           <th>Time</th>
                           <th>Action</th>
                           <th>Changes (Old)</th>
                           <th>Changes (New)</th>
                           <th>Status</th>
                           <th>Remark</th>
                           <th>Action Officer</th>
                        </tr>
                     </thead>
                  </table>
               </div>
            </div>
         </div> <!-- Datatable end-->
      </div>


</section>
{% endblock %}

{% block extrascript %}
   <script type="text/javascript" src="{% static 'src/js/requests/track.js' %}"></script>
{% endblock %}