trackit/core/urls.py
from django.urls import path
from rest_framework import routers
from .api import UserViewSet, GroupViewSet, UserUpdateAPIView, UserProfileViewSet, ChangePasswordAPIView, RegisterViewSet, UserVerificationViewSet, UserListViewSet, VerifyUserViewSet, DeclineVerificationViewSet
from . import views


router = routers.DefaultRouter()
router.register('api/core/user', UserViewSet)
router.register('api/core/all/user', UserListViewSet)
router.register('api/core/group', GroupViewSet)
router.register('api/core/user-profile', UserProfileViewSet)
router.register('api/auth/registration', RegisterViewSet)
router.register('api/core/all/verification', UserVerificationViewSet)
router.register('api/core/verify/user', VerifyUserViewSet)
router.register('api/core/decline/user', DeclineVerificationViewSet)

urlpatterns = [
   path('', views.home, name='home'),
   path('registration/', views.register, name='register'),
   path('verification/', views.verification, name='verification'),
   path('core/group', views.group_list, name='group_list'),
   path('core/user', views.user_list, name='user_list'),
   path('core/user/<int:pk>/profile', views.user_profile, name='user_profile'),

   path('api/core/user/<int:pk>/change-password/', ChangePasswordAPIView.as_view(), name='change-password'),
   path('core/user/<int:pk>/update', UserUpdateAPIView.as_view(), name='user-update'),
]

urlpatterns += router.urls

trackit/trackit/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

from core import views

urlpatterns = [
   path('admin/', admin.site.urls),
   path('accounts/', include('django.contrib.auth.urls')),
   path('api-auth/', include('rest_framework.urls')),

   path('', include('core.urls')),
   path('', include('config.urls')),
   path('', include('requests.urls')),
   path('', include('announcement.urls')),
   path('', include('events.urls')),
   path('', include('tasks.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  
handler403 = 'core.views.forbidden'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.unexpected_error'

trackit/config/models.py
from django.db import models
from core.models import User
from django.contrib.auth.models import Group
from easyaudit.models import CRUDEvent

# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=255)
    department_head = models.ForeignKey(User, related_name='dept_head', on_delete=models.CASCADE, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class CategoryType(models.Model):
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
class Category(models.Model):
    name = models.CharField(max_length=255)
    category_type = models.ForeignKey(CategoryType, related_name='category_types', on_delete=models.CASCADE)
    groups = models.ManyToManyField(Group, related_name='category_groups', blank=True)
    is_active = models.BooleanField(default=True)
        
    def __str__(self):
        return self.name
    
class Status(models.Model):
    name = models.CharField(max_length=255)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Remark(models.Model):
    remark = models.CharField(max_length=100, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    ticket = models.ForeignKey('requests.Ticket', related_name='remarks', on_delete=models.CASCADE)
    action_officer = models.ForeignKey(User, related_name='all_remarks', on_delete=models.CASCADE)
    log = models.OneToOneField(CRUDEvent, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, related_name='statuses', on_delete=models.CASCADE)
    is_approve = models.BooleanField(null=True)
    is_pass = models.BooleanField(null=True)

    def __str__(self):
        return self.remark

class Tour(models.Model):
    user = models.ForeignKey(User, related_name='tourist', on_delete=models.CASCADE)
    is_explore_main = models.BooleanField(default=False)
    is_explore_req_list = models.BooleanField(default=False)
    is_explore_req_new = models.BooleanField(default=False)
    is_explore_req_view = models.BooleanField(default=False)
    is_explore_req_detail = models.BooleanField(default=False)
    is_explore_profile = models.BooleanField(default=False)
    is_explore_task = models.BooleanField(default=False)

trackit/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

def upload_document_url(instance, filename):
   user = str(instance.user.username)
   return "verification/{0}/{1}/".format(user, filename) 

class User(AbstractUser):
   department = models.ForeignKey('config.Department', null=True, on_delete=models.CASCADE)
   middle_name = models.CharField(max_length=50, blank=True)
   suffix = models.CharField(max_length=5, blank=True)
   contact_no = models.CharField(max_length=100, blank=True)
   license_no = models.CharField(max_length=25, blank=True)

   verified_by = models.ForeignKey('self', null=True, related_name="verifier", on_delete=models.CASCADE)
   verified_at = models.DateTimeField(null=True)
   is_verified = models.BooleanField(null=True)
   remarks = models.CharField(max_length=100, blank=True)

   created_by = models.ForeignKey('self', null=True, related_name="creator", on_delete=models.CASCADE)
   modified_by = models.ForeignKey('self', null=True, related_name="modifier", on_delete=models.CASCADE)
   modified_at = models.DateTimeField(auto_now=True)

   def __str__(self):
      return '%s %s' % (self.first_name, self.last_name)
   
   class Meta:
      permissions = (
         ('change_user_password', 'Can change user password'),
         ('verify_user', 'Can verify user'),
      )

class UserVerification(models.Model):
   file = models.FileField(upload_to=upload_document_url)
   file_name = models.CharField(max_length=255, blank=True)
   file_type = models.CharField(max_length=255)
   uploaded_at = models.DateTimeField(auto_now_add=True)
   user = models.ForeignKey(User, related_name='documents', on_delete=models.CASCADE)

trackit/events/models.py
from django.db import models
from datetime import datetime, date
from core.models import User
from requests.models import Ticket, RequestForm

# Create your models here.
class Event(models.Model):
    title = models.CharField(max_length=155)
    subject = models.CharField(max_length=255, blank=True)
    event_for = models.ForeignKey(RequestForm, related_name='events', on_delete=models.CASCADE)
    highlight = models.CharField(max_length=50, blank=True)
    created_by = models.ForeignKey(User, related_name="event_creator", on_delete=models.CASCADE)
    modified_by = models.ForeignKey(User, related_name="event_modifier", on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_dates(self):
        scheduled_dates = EventDate.objects.select_related('event').filter(event=self).order_by('date').values('date')
        return scheduled_dates

    def get_num_participants(self):
        participants = EventTicket.objects.select_related('event', 'ticket').filter(event=self)
        return participants.count()

class EventDate(models.Model):
    event = models.ForeignKey(Event, related_name='dates', on_delete=models.CASCADE)
    date = models.DateField(null=False, blank=False)
    time_start = models.TimeField(null=False, blank=False)
    time_end = models.TimeField(null=False, blank=False)
    venue = models.CharField(max_length=255, null=False, blank=False)
    address = models.URLField(max_length=200, blank=True)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return '%s, %s-%s' % (self.date, self.time_start, self.time_end)

    def date_start(self):
        return '%s %s' % (self.date, self.time_start)

    def date_end(self):
        return '%s %s' % (self.date, self.time_end)
    
    @property
    def is_past_due(self):
        now = datetime.now().strftime("%Y-%m-%d %H:%M")
        date_today = datetime.strptime(now, "%Y-%m-%d %H:%M")
        date_start = datetime.combine(self.date, self.time_start)
        date_end = datetime.combine(self.date, self.time_end)
        return date_today > date_start and date_today > date_end
    
    class Meta:
        unique_together = [['event', 'date', 'time_start', 'time_end']]

class EventTicket(models.Model):
    ticket = models.ForeignKey(Ticket, related_name="events", on_delete=models.CASCADE)
    scheduled_event = models.ForeignKey(EventDate, related_name='participants', on_delete=models.CASCADE)
    attended = models.BooleanField(null=True)
    remarks = models.CharField(max_length=100, null=True, blank=True)
    is_reschedule = models.BooleanField(default=False)

trackit/requests/models.py
import uuid
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_mysql.models import JSONField
from django.contrib.auth.models import Group
from easyaudit.models import CRUDEvent
from config.models import Department, Category, Status, CategoryType
from core.models import User


def upload_file_url(instance, filename):
    ticket_no = str(instance.ticket.ticket_no)
    return "attachments/{0}/{1}/".format(ticket_no, filename) 

# Create your models here.
class RequestForm(models.Model):
    name =  models.CharField(max_length=255)
    prefix = models.CharField(max_length=5)
    color = models.CharField(max_length=50, blank=True)
    status = models.ManyToManyField(Status, related_name='forms', blank=True, through='RequestFormStatus')
    fields = JSONField()
    group = models.ManyToManyField(Group, related_name='groups', blank=True)
    category_types = models.ManyToManyField(CategoryType, related_name='form_types', blank=True)
    guide = models.CharField(max_length=255, blank=True)
    is_active = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

# Main Service Request Model
class Ticket(models.Model):
    ticket_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    ticket_no = models.CharField(max_length=25, blank=True)
    description = models.CharField(max_length=255)
    reference_no = models.CharField(max_length=15, blank=True)
    form_data = JSONField()
    
    request_form = models.ForeignKey(RequestForm, related_name='formtype_tickets', on_delete=models.PROTECT)
    category = models.ManyToManyField(Category, related_name='category_tickets', blank=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    requested_by = models.ForeignKey(User, related_name='user_tickets', on_delete=models.PROTECT)
    status = models.ForeignKey(Status, related_name='status_tickets', on_delete=models.SET_NULL, null=True, blank=True)

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        permissions = [
            ("generate_reference", "Can generate reference no"),
        ]

    def __str__(self):
        return str(self.ticket_id)

class RequestFormStatus(models.Model):
    form = models.ForeignKey(RequestForm, related_name="request_forms", on_delete=models.CASCADE)
    status = models.ForeignKey(Status, related_name='form_statuses', on_delete=models.CASCADE)
    officer = models.ManyToManyField(User, related_name='status_officers', blank=True)
    order = models.PositiveSmallIntegerField(null=True, blank=True)
    is_client_step =  models.BooleanField(default=False)
    is_head_step =  models.BooleanField(default=False)
    has_pass_fail = models.BooleanField(default=False)
    has_approving = models.BooleanField(default=False)
    has_event = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    
    @property
    def is_not_for_task(self):
        return not self.is_client_step and not self.is_head_step and not self.officer.exists()

class Attachment(models.Model):
    file = models.FileField(upload_to=upload_file_url)
    file_name = models.CharField(max_length=255, blank=True)
    file_type = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    ticket = models.ForeignKey(Ticket, related_name='attachments_ticket', on_delete=models.CASCADE)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    uploaded_by = models.ForeignKey('core.User', related_name='attachments_user', on_delete=models.CASCADE)

class Notification(models.Model):
    log = models.ForeignKey(CRUDEvent, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notifications')
    unread = models.BooleanField(default=True)

class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='all_comments')
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, related_name='comments')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.ticket, self.user.get_full_name())

trackit/templates/snippets/footer.html
<footer class="main-footer p-2 d-flex align-items-center justify-content-md-start">
    <div class="px-2"><p class="m-0 text-xs font-weight-bold text-muted">© 2021</p></div>
    <div class="px-2"><p class="m-0 text-xs font-weight-bold"><a class="text-muted" href="https://spmc.doh.gov.ph/">Southern Philippines Medical Center</a></p></div>
    <div class="px-2"><p class="m-0 text-xs font-weight-bold text-muted">IHOMS</p></div>
    {% comment %} <div class="px-2"><p class="m-0 text-xs font-weight-bold text-muted">AdminLTE.io</p></div> {% endcomment %}
    {% comment %} <p class="m-0 text-xs"><strong>Version</strong> 1.0</p> {% endcomment %}
</footer>

trackit/templates/snippets/navbar.html
{% load static %}

{% block extrastyle %}
<link rel="stylesheet" href="{% static 'src/css/navbar.css' %}">
{% endblock %}

<nav class="main-header navbar navbar-expand navbar-white navbar-light">
   <!-- Left navbar links -->
   <ul class="navbar-nav">
      <li class="nav-item">
         <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item">
         <a href="{% static 'user_guide_2_0.pdf' %}" class="nav-link" id="intro_guide" target="_blank"><i class="fas fa-book d-sm-none"></i> <span class="d-none d-sm-inline">User Guide<span></a>
      </li>
      <li class="nav-item">
         <a href="#" class="nav-link tour-me" id="intro_explore"><i class="far fa-question-circle d-sm-none"></i> <span class="d-none d-sm-inline" >Help<span></a>
      </li>
      
      {% comment %} <li class="nav-item">
         <a href="{% url 'home' %}" class="nav-link">Home</a>
      </li> {% endcomment %}
   </ul>

   {% block comment %}
   <!-- SEARCH FORM -->
   <!-- <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search"
                aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form> -->
   {% endblock %}

   <!-- Right navbar links -->
   <ul class="navbar-nav ml-auto ">
      <li class="nav-item dropdown intro-nav-notification" id="intro_notification">
         <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="far fa-bell"></i>
            <span class="badge badge-danger navbar-badge new-notifications-count"></span>
         </a>
         <div class="dropdown-menu dropdown-menu-xl dropdown-menu-right dropdown-notifications-div">
            <div class="dropdown-item dropdown-header dropdown-notifications-title shadow-sm">
               <div class="d-flex align-items-center">
                  <p class="font-weight-bold text-sm m-0">Notifications</p>
                  <span class="ml-auto"> <button class="btn btn-xs btn-link btn-link-orange m-0 p-0" id="clear-all-notifications">Clear all</button> </span>
               </div>
               <div class="mt-2">
                 <nav>
                  <!-- Navigation -->
                  <div class="nav nav-pills" id="nav-tab" role="tablist">
                     <a class="nav-item nav-link active d-flex align-items-center" id="nav-personal-tab" data-toggle="tab" href="#all"
                        role="tab" aria-controls="nav-personal" aria-selected="true">All 
                        <span class="badge badge-notification notifications-count ml-1"></span> 
                     </a>
                  </div>
               </nav>
               </div>
            </div>
            <div class="dropdown-body p-1"></div>
            <input type="hidden" id="notification-nextpage-url"> <!-- Hidden input for infinite notification scroll -->
         </div>
      </li>
      <li class="nav-item intro-nav-logout" id="intro_logout">
         <a href="{% url 'logout' %}" class="nav-link nav-user" data-user-id="{{request.user.id}}" data-user-fullname="{{request.user.get_full_name}}">
            <span class="d-none d-sm-inline ml-1">Sign out</span> <i class="fas fa-sign-out-alt"></i>
         </a>
      </li>
   </ul>
</nav>

trackit/templates/snippets/scripts.html
{% load static %}

<!-- JQuery -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

<!-- Axios -->
<script src="{% static 'vendor/axios/axios.min.js' %}"></script>

<!-- Bootstrap tooltips -->
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>

<!-- Boostrap -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Select2 -->
<script src="{% static 'vendor/select2/js/select2.full.min.js' %}"></script>

<!-- Datatables -->
<script src="{% static 'vendor/datatables/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'vendor/datatables/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'vendor/datatables/datatables-plugins/dataTables.render.ellipsis.js' %}"></script>

<!-- Sweet Alert 2 -->
<script src="{% static 'vendor/sweetalert2/js/sweetalert2.all.min.js' %}"></script>

<!-- Moment -->
<script src="{% static 'vendor/moment/moment.js' %}"></script>

<!-- Boostrap DateTime -->
<script src="{% static 'vendor/bootstrap-datetime/js/bootstrap-datetime.min.js' %}"></script>

<!-- AdminLTE -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>

<!-- Intro JS -->
<script src="{% static 'vendor/intro/intro.min.js' %}"></script>

<!-- Custom Libraries -->
<script src="{% static 'lib/js/library.js' %}"></script>
<script src="{% static 'lib/js/tour.js' %}"></script>

<!-- Navbar -->
<script type="text/javascript" src="{% static 'src/js/navbar.js' %}"></script>

<!-- WebSocket -->
<script src="{% static 'lib/js/websocket-notification.js' %}"></script>

trackit/templates/snippets/sidebar.html
{% load static %}

<!-- Sidebar -->
<aside class="main-sidebar elevation-4 sidebar-dark-orange">
   <!-- Brand Logo -->
   <a href="{% url 'home' %}" class="brand-link text-center">
      <span class="brand-text font-weight-light">Track-It </span>
   </a>

   <!-- Sidebar -->
   <div class="sidebar">
      {% with request.resolver_match.url_name as url %}
      <a href="{% url 'user_profile' pk=user.id %}" id="intro_profile"> 
         <div class="user-panel mt-3 pb-3 mb-3 d-flex align-items-center">
            <div class="mx-2">
               <div class="img-circle">{{user.first_name|make_list|first}}{{user.last_name|make_list|first}}</div>
               <div class="online-status bg-success d-none"></div>
            </div>
            <div class="info d-flex flex-column p-0 mx-2">
               <p class="d-flex align-items-center text-sm m-0 {% if url == 'user_profile' %} text-light {% endif %}" >
                  {{user.first_name}} {{user.last_name}}
                  {% if user.is_verified %}
                  {% if user.is_superuser %}
                     <span class="fa-stack text-orange verification-status ml-1">
                        <i class="fas fa-certificate fa-stack-2x"></i>
                        <i class="fas fa-check fa-stack-1x fa-inverse"></i>
                     </span>
                  {% endif %}
                  {% endif %}
               </p>
               <p class="text-secondary m-0 text-xs">See your profile</p>
            </div>
         </div>
      </a>
      
      <!-- Sidebar Menu -->
      <nav class="mt-2">
         <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent text-sm" data-widget="treeview" role="menu"
            data-accordion="false">

            {% comment %} <li class="nav-header text-muted">NAVIGATION</li> {% endcomment %}
            <li class="nav-item" id="intro_dashboard">
               <a href="{% url 'home' %}" class="nav-link {% if url == 'home' %} active {% endif %}">
                  <i class="nav-icon fas fa-rocket"></i>
                  <p> Dashboard</p>
               </a>
            </li>

            {% comment %} <!-- // // // // USER GUIDE MODULE --> 
            <li class="nav-item" id="intro_guide">
               <a href="{% static 'user_guide_2_0.pdf' %}"
                  class="nav-link" target="_blank">
                  <i class="nav-icon fas fa-book"></i>
                  <p> User Guide</p>
               </a>
            </li> {% endcomment %}
            
            {% if user.is_verified %}      

            <!-- // // // // TASKS MODULE --> 
            <li class="nav-item" id="intro_tasks">
               <a href="{% url 'mytasks' %}" class="nav-link {% if url == 'mytasks' %} active {% endif %}">
                  <div class="d-flex align-items-center mr-auto">
                     <i class="nav-icon fas fa-tasks"></i>
                     <p> My Tasks</p>
                  </div>
                  <span class="badge badge-pill badge-secondary mx-2" id="badge_task"></span>
               </a>
            </li>

            {% if request.user.is_superuser or request.user.is_staff %}
            <li class="nav-header">menu</li>

            <!-- // // // // USERS AND GROUPS MODULE --> 
            {% if perms.auth.view_group or perms.core.view_user %}
            <li
               class="nav-item {% if url == 'group_list' or url == 'user_list' %} menu-open {% endif %}">
               <a href="#"
                  class="nav-link {% if url == 'group_list' or url == 'user_list' %} active {% endif %}">
                  <i class="nav-icon fas fa-users"></i>
                  <p>
                     Users & Groups
                     <i class="right fas fa-angle-left"></i>
                  </p>
               </a>
               <ul class="nav nav-treeview">
                  {% if perms.core.view_user %}
                  <li class="nav-item">
                     <a href="{% url 'user_list' %}" class="nav-link {% if url == 'user_list' %} active {% endif %}">
                        <i class="nav-icon far fa-circle"></i>
                        <p>User</p>
                     </a>
                  </li>
                  {% endif %}
                  {% if perms.auth.view_group %}
                  <li class="nav-item">
                     <a href="{% url 'group_list' %}" class="nav-link {% if url == 'group_list' %} active {% endif %}">
                        <i class="nav-icon far fa-circle"></i>
                        <p>Group</p>
                     </a>
                  </li>
                  {% endif %}
               </ul>
            </li>
            {% endif %}
         
            <!-- // // // // CONFIG MODULE --> 
            {% if perms.config.view_department or perms.config.view_category or perms.config.view_categorytype or perms.requests.view_requestform or perms.config.view_status %}
            <li
               class="nav-item {% if url == 'department' or url == 'category' or url == 'types' or url == 'forms' or url == 'status_list'  %} menu-open {% endif %}">
               <a href="#"
                  class="nav-link {% if url == 'department' or url == 'category' or url == 'types' or url == 'forms' or url == 'status_list' %} active {% endif %}">
                  <i class="nav-icon fas fa-th-large"></i>
                  <p>
                     Library
                     <i class="right fas fa-angle-left"></i>
                  </p>
               </a>
               <ul class="nav nav-treeview">
                  {% if perms.config.view_department %}
                  <li class="nav-item">
                     <a href="{% url 'department' %}" class="nav-link {% if url == 'department' %} active {% endif %}">
                        <i class="nav-icon far fa-circle"></i>
                        <p>Departments</p>
                     </a>
                  </li>
                  {% endif %}
                  {% if perms.config.view_category %}
                  <li class="nav-item">
                     <a href="{% url 'category' %}" class="nav-link {% if url == 'category' %} active {% endif %}">
                        <i class="nav-icon far fa-circle"></i>
                        <p>Categories</p>
                     </a>
                  </li>
                  {% endif %}
                  {% if perms.config.view_categorytype %}
                  <li class="nav-item">
                     <a href="{% url 'types' %}" class="nav-link {% if url == 'types' %} active {% endif %}">
                        <i class="nav-icon far fa-circle"></i>
                        <p>Category Types</p>
                     </a>
                  </li>
                  {% endif %}
                  {% if perms.requests.view_requestform %}
                  <li class="nav-item">
                     <a href="{% url 'forms' %}" class="nav-link {% if url == 'forms' %} active {% endif %}">
                        <i class="nav-icon far fa-circle"></i>
                        <p>Forms</p>
                     </a>
                  </li>
                  {% endif %}
                  {% if perms.config.view_status %}
                  <li class="nav-item">
                     <a href="{% url 'status_list' %}"
                        class="nav-link {% if url == 'status_list' %} active {% endif %}">
                        <i class="nav-icon far fa-circle"></i>
                        <p>Status</p>
                     </a>
                  </li>
                  {% endif %}
               </ul>
            </li>
            {% endif %}

            <!-- // // // // EVENTS MODULE --> 
            {% if perms.events.view_event %}
            <li class="nav-item {% if url == 'event' or  url == 'create_event' or url == 'event_calendar' or url == 'view_event' or url == 'change_event' %} menu-open {% endif %}">
               <a href="#" class="nav-link {% if url == 'event' or  url == 'create_event' or url == 'event_calendar' or url == 'view_event' or url == 'change_event' %} active {% endif %}">
                  <i class="nav-icon fas fa-calendar-alt"></i>
                  <p>
                     Events
                     <i class="right fas fa-angle-left"></i>
                  </p>
               </a>
               <ul class="nav nav-treeview">
                  <li class="nav-item">
                     <a href="{% url 'event_calendar' %}"
                        class="nav-link {% if url == 'event_calendar'  %} active {% endif %}">
                        <i class="nav-icon far fa-circle"></i>
                        <p>Calendar</p>
                     </a>
                  </li>
                  <li class="nav-item">
                     <a href="{% url 'event' %}"
                        class="nav-link {% if url == 'event' or  url == 'create_event' or url == 'view_event' or url == 'change_event' %} active {% endif %}">
                        <i class="nav-icon far fa-circle"></i>
                        <p>Manage</p>
                     </a>
                  </li>
               </ul>
            </li>
            {% endif %}

            <!-- // // // // ANNOUNCEMENT MODULE --> 
            {% if perms.announcement.view_article %}
            <li class="nav-item">
               <a href="{% url 'announcement' %}" class="nav-link {% if url == 'announcement' or  url == 'create_article' or  url == 'view_article' or  url == 'change_article' %} active {% endif %}">
                  <i class="nav-icon fas fa-bullhorn"></i>
                  <p> Announcement</p>
               </a>
            </li>
            {% endif %}
            {% endif %}


            <!-- // // // // REQUESTS MODULE --> 
            {% if perms.requests.add_ticket or perms.requests.view_ticket %}
            <li class="nav-header">Request</li>
            {% if perms.requests.view_ticket %}
            <li class="nav-item"  id="intro_request">
               <a href="{% url 'ticket' %}"
                  class="nav-link {% if url == 'ticket' or url == 'detail_ticket' or url == 'view_ticket' %} active {% endif %}">
                  <i class="nav-icon fas fa-list"></i>
                  <p>All Requests</p>
               </a>
            </li>
            {% endif %}
            <li class="nav-item">
               <a href="{% url 'ticket_log_list' %}"
                  class="nav-link {% if url == 'ticket_log_list' %} active {% endif %}" id="intro_track_request">
                  <i class="nav-icon fas fa-paper-plane"></i>
                  <p>Track</p>
               </a>
            </li>
            {% if perms.requests.add_ticket %}
            <li class="nav-item">
               <a href="{% url 'create_ticket' %}"
                  class="nav-link nav-link-add {% if url == 'create_ticket' %}active{% endif %}" id="intro_create_request">
                  <i class="nav-icon nav-icon-add  fas fa-plus"></i>
                  <p>Create a Request</p>
               </a>
            </li>
            {% endif %}
            {% endif %}
            {% endif %}
         </ul>
      </nav>
      {% endwith %}
      <!-- /.sidebar-menu -->
   </div>
   <!-- /.sidebar -->
</aside>