trackit/config/urls.py
from django.urls import path
from rest_framework import routers
from .api import DepartmentViewSet, CategoryViewSet, CategoryListViewSet, CategoryListDropdownViewSet, CategoryTypeViewSet, StatusViewSet, TourViewSet
from . import views

router = routers.DefaultRouter()
router.register('api/config/department', DepartmentViewSet, basename='Department')
router.register('api/config/category', CategoryViewSet, basename='Category')
router.register('api/config/list/category/dropdown', CategoryListDropdownViewSet, basename='CategoryListDropdown')
router.register('api/config/list/category', CategoryListViewSet, basename='CategoryList')
router.register('api/config/categorytype', CategoryTypeViewSet, basename='CategoryType')
router.register('api/config/status', StatusViewSet, basename='Status')
router.register('api/config/tour', TourViewSet, basename='Tour')

urlpatterns = [
   path('config/department', views.department, name='department'),
   path('config/category', views.category, name='category'),
   path('config/types', views.types, name='types'),
   path('config/forms', views.forms, name='forms'),
   path('config/status', views.status_list, name='status_list'),
]

urlpatterns += router.urls

trackit/core/urls.py
from django.urls import path
from rest_framework import routers
from .api import UserViewSet, GroupViewSet, UserUpdateAPIView, UserProfileViewSet, ChangePasswordAPIView, RegisterViewSet, UserVerificationViewSet, UserListViewSet, VerifyUserViewSet, DeclineVerificationViewSet
from . import views


router = routers.DefaultRouter()
router.register('api/core/user', UserViewSet)
router.register('api/core/all/user', UserListViewSet)
router.register('api/core/group', GroupViewSet)
router.register('api/core/user-profile', UserProfileViewSet)
router.register('api/auth/registration', RegisterViewSet)
router.register('api/core/all/verification', UserVerificationViewSet)
router.register('api/core/verify/user', VerifyUserViewSet)
router.register('api/core/decline/user', DeclineVerificationViewSet)

urlpatterns = [
   path('', views.home, name='home'),
   path('registration/', views.register, name='register'),
   path('verification/', views.verification, name='verification'),
   path('core/group', views.group_list, name='group_list'),
   path('core/user', views.user_list, name='user_list'),
   path('core/user/<int:pk>/profile', views.user_profile, name='user_profile'),

   path('api/core/user/<int:pk>/change-password/', ChangePasswordAPIView.as_view(), name='change-password'),
   path('core/user/<int:pk>/update', UserUpdateAPIView.as_view(), name='user-update'),
]

urlpatterns += router.urls

trackit/trackit/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

from core import views

urlpatterns = [
   path('admin/', admin.site.urls),
   path('accounts/', include('django.contrib.auth.urls')),
   path('api-auth/', include('rest_framework.urls')),

   path('', include('core.urls')),
   path('', include('config.urls')),
   path('', include('requests.urls')),
   path('', include('announcement.urls')),
   path('', include('events.urls')),
   path('', include('tasks.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  
handler403 = 'core.views.forbidden'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.unexpected_error'

trackit/config/models.py
from django.db import models
from core.models import User
from django.contrib.auth.models import Group
from easyaudit.models import CRUDEvent

# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=255)
    department_head = models.ForeignKey(User, related_name='dept_head', on_delete=models.CASCADE, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class CategoryType(models.Model):
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
class Category(models.Model):
    name = models.CharField(max_length=255)
    category_type = models.ForeignKey(CategoryType, related_name='category_types', on_delete=models.CASCADE)
    groups = models.ManyToManyField(Group, related_name='category_groups', blank=True)
    is_active = models.BooleanField(default=True)
        
    def __str__(self):
        return self.name
    
class Status(models.Model):
    name = models.CharField(max_length=255)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Remark(models.Model):
    remark = models.CharField(max_length=100, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    ticket = models.ForeignKey('requests.Ticket', related_name='remarks', on_delete=models.CASCADE)
    action_officer = models.ForeignKey(User, related_name='all_remarks', on_delete=models.CASCADE)
    log = models.OneToOneField(CRUDEvent, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, related_name='statuses', on_delete=models.CASCADE)
    is_approve = models.BooleanField(null=True)
    is_pass = models.BooleanField(null=True)

    def __str__(self):
        return self.remark

class Tour(models.Model):
    user = models.ForeignKey(User, related_name='tourist', on_delete=models.CASCADE)
    is_explore_main = models.BooleanField(default=False)
    is_explore_req_list = models.BooleanField(default=False)
    is_explore_req_new = models.BooleanField(default=False)
    is_explore_req_view = models.BooleanField(default=False)
    is_explore_req_detail = models.BooleanField(default=False)
    is_explore_profile = models.BooleanField(default=False)
    is_explore_task = models.BooleanField(default=False)

trackit/config/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render
from django.contrib.auth.models import Group

from .models import CategoryType, Status
from core.models import User
from requests.models import RequestForm

from core.decorators import user_is_verified, user_is_staff_member

# Create your views here.
@login_required
@user_is_verified
@user_is_staff_member
@permission_required('config.view_department', raise_exception=True)
def department(request):
   users = User.objects.filter(is_active=True).order_by('first_name')
   context = {'users': users}
   return render(request, 'pages/config/department.html', context)

@login_required
@user_is_verified
@user_is_staff_member
@permission_required('config.view_category', raise_exception=True)
def category(request):
   types = CategoryType.objects.all().order_by('name')
   select_types = types.filter(is_active=True)
   groups = Group.objects.all().order_by('name')
   context = {'types': types, 'select_types': select_types, 'groups':groups}
   return render(request, 'pages/config/category.html', context)

@login_required
@user_is_verified
@user_is_staff_member
@permission_required('config.view_categorytype', raise_exception=True)
def types(request):
   return render(request, 'pages/config/types.html')

@login_required
@user_is_verified
@user_is_staff_member
@permission_required('requests.view_requestform', raise_exception=True)
def forms(request):
   statuses = Status.objects.filter(is_active=True).order_by('name')
   types = CategoryType.objects.filter(is_active=True).order_by('name')
   groups = Group.objects.all().order_by('name')
   users = User.objects.filter(is_active=True, is_staff=True).order_by('first_name')
   context = {'statuses': statuses, 'types':types, 'groups': groups, 'users' : users}
   return render(request, 'pages/config/forms.html', context)

@login_required
@user_is_verified
@user_is_staff_member
@permission_required('config.view_status', raise_exception=True)
def status_list(request):
   return render(request, 'pages/config/status.html')

trackit/templates/pages/config/category.html
{% extends '../../base.html' %}
{% load static %}

{% block title %} Categories | {% endblock %}

{% block content %}
<!-- Content Header -->
<section class="content-header">
   <div class="container-fluid">
      <div class="row mb-2">
         <div class="col-sm-6">
            <h5 class="font-weight-bolder">Categories</h5>
         </div>
         <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right text-xs">
               <li class="breadcrumb-item"><a href="{% url 'home' %}" class="text-orange"><i
                        class="fas fa-home"></i></a></li>
               <li class="breadcrumb-item">Library</li>
               <li class="breadcrumb-item">Categories</li>
               <li class="breadcrumb-item active">List</li>
            </ol>
         </div>
      </div>
   </div>
</section>

<!-- /.content -->
<section class="content">
   <div class="container-fluid">

      <!-- Content Filters, Search and Create Section -->
      <div class="d-flex mb-1">
         <div class="dropdown dropdown-filter mr-2">
            <button class="btn btn-sm btn-light shadow-sm dropdown-filter-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <i class="fas fa-xs fa-filter m-0 d-inline d-md-none"></i>
               <span class="d-none d-md-inline pl-1">Filter <i class="fas fa-caret-down ml-1"></i></span>
            </button>
            <div class="dropdown-menu dropdown-menu-lg dropdown-filter-menu">
               <form id="form-filter">
                  <div class="p-3">
                     <div class="form-group mb-1">
                        <label for="active-filter">By Type </label>
                        <select class="form-control form-control-sm select-filter" id="type-filter">
                           <option value="">All</option>
                           {% for type in types %}
                           <option value={{type.id}}>{{type.name}}</option>
                           {% endfor %}
                        </select>
                     </div>
                     <div class="form-group mb-1">
                        <label for="active-filter">By Active </label>
                        <select class="form-control form-control-sm select-filter" id="active-filter">
                           <option value="">All</option>
                           <option value="0">Yes</option>
                           <option value="1">No</option>
                        </select>
                     </div>
                     <div class="form-group mb-1">
                        <label for="active-filter">By Group </label>
                        <select class="form-control form-control-sm select-filter-multiple" id="group-filter" multiple>
                           {% for group in groups %}
                           <option value={{group.id}}>{{group.name}}</option>
                           {% endfor %}
                        </select>
                     </div>
                  </div>
                  <div class="dropdown-divider"></div>
                  <div class="d-flex flex-row-reverse pt-2 pb-2 pl-3 pr-3">
                     <div><button class="btn btn-sm btn-orange ml-1" id="btn_apply"> <span>Apply</span> </button></div>
                     <div><a class="btn btn-sm btn-link text-secondary" id="btn_clear"> <span>Clear</span> </a></div>
                     <div class="mr-auto"><a class="btn btn-sm btn-link text-secondary pl-0" id="close_dropdown"> <span>Close</span> </a></div>
                  </div>
               </form>
            </div>
         </div>
         <div class="col-auto col-lg-3 p-0"> 
            <div class="input-group shadow-sm">
               <input type="search" class="form-control form-control-sm" placeholder="Search" id="search-input">
               <div class="input-group-append">
                 <button class="btn btn-sm btn-outline-secondary" type="button" id="execute-search">
                     <i class="fas fa-sm fa-search"></i>
                  </button>
               </div>
            </div>
         </div>
         <div class="ml-auto">
            {% if perms.config.add_category %}
            <button class="btn btn-xs btn-orange btn-new shadow-sm" id="btn-create-category"><i class="fas fa-xs fa-plus"></i> <span class="d-none d-sm-inline ml-1">Add Category</span></button>
            {% endif %}
         </div>
      </div>

      <!-- Table  -->
      <div class="row">
         <div class="col-12 col-sm-12">
            <div class="card shadow-sm mt-2 mb-2">
               <div class="card-body p-0">
                  <template id="table_spinner">
                     <div class="d-flex justify-content-center align-items-center">
                        <div class="spinner-border text-orange mr-2" style="width: 1.2rem; height: 1.2rem;" role="status">
                        </div>
                        <span class="text-secondary">Fetching...</span>
                     </div>
                  </template>
                  <table id="dt_category" class="table table-hover" width="100%">
                     <thead>
                        <tr>
                           <th>Name</th>
                           <th>Groups</th>
                           <th>Category Type</th>
                           <th>Is Active</th>
                        </tr>
                     </thead>
                  </table>
               </div>
            </div>
         </div>
      </div>

   </div>
   <input type="hidden" id="changeCategoryHidden" value="{% if perms.config.change_category %}true{% else %}false{% endif %}">

</section>
{% endblock %}

{% block modal %}
<!-- Create -->
<div class="modal fade" id="modalCategory" tabindex="-1" role="dialog" aria-labelledby="formModal" aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content text-sm">
         <div class="modal-header">
            <h6 class="modal-title"></h6>
            <!-- <button type="button" class="" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button> -->
         </div>
         <div class="modal-body">
            <form id="form">
               <div class="form-group">
                  <label for="nameHelp">Name <span class="text-danger">*</span></label>
                  <input type="text" class="form-control form-control-sm" id="txt_categoryname"
                     aria-describedby="nameHelp" placeholder="Enter category name">
                  <small class="error-info" id="categoryname_error"></small>
               </div>
               <div class="form-group">
                  <label>Category Type <span class="text-danger">*</span></label>
                  <select class="form-control form-control-sm" id="select2_categorytypes" style="width: 100%">
                     <option></option>
                     {% for type in select_types %}
                     <option value={{type.id}}>{{type.name}}</option>
                     {% endfor %}
                  </select>
                  <small class="error-info" id="categorytypes_error"></small>
               </div>
               <div class="form-group"> <!-- Groups -->
                  <label>Groups</label>
                  <select class="form-control form-control-sm" id="select2_groups" style="width: 100%" multiple>
                     <option></option>
                     {% for group in groups %}
                     <option value={{group.id}}>{{group}}</option>
                     {% endfor %}
                  </select>
                  <small class="error-info"></small>
               </div>
               <div class="icheck-material-green">
                  <input type="checkbox" id="chk_status" checked />
                  <label for="chk_status">Is Active</label>
               </div>
            </form>
         </div>
         <div class=" modal-footer">
            <button type="button" class="btn btn-sm btn-light m-0 mr-2" id="btn_cancel" data-dismiss="modal"><span>Cancel</span></button>
            <button type="submit" class="btn btn-sm btn-orange m-0" id="btn_save"><span>Save</span></button>
         </div>
      </div>
   </div>
</div>

{% endblock %}

{% block extrascript %}
<script type="text/javascript" src="{% static 'src/js/config/category.js' %}"></script>
{% endblock %}

trackit/templates/pages/config/department.html
{% extends '../../base.html' %}
{% load static %}

{% block title %} Departments | {% endblock %}

{% block content %}
<!-- Content Header -->
<section class="content-header">
   <div class="container-fluid">
      <div class="row mb-2">
         <div class="col-sm-6">
            <h5 class="font-weight-bolder">Departments </h5>
         </div>
         <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right text-xs">
               <li class="breadcrumb-item"><a href="{% url 'home' %}" class="text-orange"><i
                        class="fas fa-home"></i></a></li>
               <li class="breadcrumb-item">Library</li>
               <li class="breadcrumb-item">Depeartments</li>
               <li class="breadcrumb-item active">List</li>
            </ol>
         </div>
      </div>
   </div>
</section>

<!-- /.content -->
<section class="content">
   <div class="container-fluid">

      <!-- Content Filters, Search and Create Section -->
      <div class="d-flex mb-1">
         <div class="dropdown dropdown-filter mr-2">
            <button class="btn btn-sm btn-light shadow-sm dropdown-filter-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <i class="fas fa-xs fa-filter m-0 d-inline d-md-none"></i>
               <span class="d-none d-md-inline pl-1">Filter <i class="fas fa-caret-down ml-1"></i></span>
            </button>
            <div class="dropdown-menu dropdown-menu-lg dropdown-filter-menu">
               <form id="form-filter">
                  <div class="p-3">
                     <div class="form-group mb-1">
                        <label for="active-filter">By Active </label>
                        <select class="form-control form-control-sm select-filter" id="active-filter">
                           <option value="">All</option>
                           <option value="0">Yes</option>
                           <option value="1">No</option>
                        </select>
                     </div>
                  </div>
                  <div class="dropdown-divider"></div>
                  <div class="d-flex flex-row-reverse pt-2 pb-2 pl-3 pr-3">
                     <div><button class="btn btn-sm btn-orange ml-1" id="btn_apply"> <span>Apply</span> </button></div>
                     <div><a class="btn btn-sm btn-link text-secondary" id="btn_clear"> <span>Clear</span> </a></div>
                     <div class="mr-auto"><a class="btn btn-sm btn-link text-secondary pl-0" id="close_dropdown"> <span>Close</span> </a></div>
                  </div>
               </form>
            </div>
         </div>
         <div class="col-auto col-lg-3 p-0"> 
            <div class="input-group shadow-sm">
               <input type="search" class="form-control form-control-sm" placeholder="Search" id="search-input">
               <div class="input-group-append">
                 <button class="btn btn-sm btn-outline-secondary" type="button" id="execute-search">
                     <i class="fas fa-sm fa-search"></i>
                  </button>
               </div>
            </div>
         </div>
         <div class="ml-auto">
            {% if perms.config.add_department %}
            <button class="btn btn-xs btn-orange btn-new shadow-sm" id="btn-create-department"><i class="fas fa-xs fa-plus"></i> <span class="d-none d-sm-inline ml-1">Add Department</span></button>
            {% endif %}
         </div>
      </div>
      
      <!-- Table -->
      <div class="row">
         <div class="col-12 col-sm-12">
            <div class="card shadow-sm mt-2 mb-2">
               <div class="card-body p-0">
                  <template id="table_spinner">
                     <div class="d-flex justify-content-center align-items-center">
                        <div class="spinner-border text-orange mr-2" style="width: 1.2rem; height: 1.2rem;" role="status">
                        </div>
                        <span class="text-secondary">Fetching...</span>
                     </div>
                  </template>
                  <table id="dt_department" class="table table-hover" width="100%">
                     <thead>
                        <tr>
                           <th>Name</th>
                           <th>Department Head</th>
                           <th>Is Active</th>
                        </tr>
                     </thead>
                  </table>
               </div>
            </div>
         </div>
      </div>

   </div>
   <input type="hidden" id="changeDepartmentHidden" value="{% if perms.config.change_department %}true{% else %}false{% endif %}">

</section>
{% endblock %}

{% block modal %}
<!-- Create -->
<div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-labelledby="formModal" aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content text-sm">
         <div class="modal-header">
            <h6 class="modal-title">Create Department</h6>
            <!-- <button type="button" class="" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button> -->
         </div>
         <div class="modal-body">
            <form id="form">
               <div class="form-group">
                  <label for="nameHelp">Department Name <span class="text-danger">*</span></label>
                  <input type="text" class="form-control form-control-sm" id="txt_deptname" aria-describedby="nameHelp"
                     placeholder="Enter department / name of office">
                  <small class="error-info" id="error-department-info"></small>
               </div>
               <div class="form-group">
                  <label>Department Head</label>
                  <select class="form-control form-control-sm" id="dd_depthead" style="width: 100%">
                     <option></option>
                     {% for user in users%}
                     <option value={{user.id}}>{{user.first_name}} {{user.last_name}}</option>
                     {% endfor %}
                  </select>
                  <small class="error-info dept-head-error"></small>
               </div>
               <div class="icheck-material-green">
                  <input type="checkbox" id="chk_status" checked />
                  <label for="chk_status">Is Active</label>
               </div>
            </form>
         </div>
         <div class=" modal-footer">
            <button type="button" class="btn btn-sm btn-light m-0 mr-2" id="btn_cancel" data-dismiss="modal"><span>Cancel</span></button>
            <button type="submit" class="btn btn-sm btn-orange m-0" id="btn_save"><span>Save</span></button>
         </div>
      </div>
   </div>
</div>

{% endblock %}

{% block extrascript %}
<script type="text/javascript" src="{% static 'src/js/config/department.js' %}"></script>
{% endblock %}

trackit/templates/pages/config/status.html
{% extends '../../base.html' %}
{% load static %}

{% block title %} Status | {% endblock %}

{% block extrastyle %}
{% endblock %}

{% block content %}
<!-- Content Header -->
<section class="content-header">
   <div class="container-fluid">
      <div class="row mb-2">
         <div class="col-sm-6">
            <h5 class="font-weight-bolder">Status</h5>
         </div>
         <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right text-xs">
               <li class="breadcrumb-item"><a href="{% url 'home' %}" class="text-orange"><i
                        class="fas fa-home"></i></a></li>
               <li class="breadcrumb-item">Library</li>
               <li class="breadcrumb-item">Status</li>
               <li class="breadcrumb-item active">List</li>
            </ol>
         </div>
      </div>
   </div>
</section>

<!-- /.content -->
<section class="content">
   <div class="container-fluid">

      <!-- Content Filters, Search and Create Section -->
      <div class="d-flex mb-1">
         <div class="dropdown dropdown-filter mr-2">
            <button class="btn btn-sm btn-light shadow-sm dropdown-filter-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <i class="fas fa-xs fa-filter m-0 d-inline d-md-none"></i>
               <span class="d-none d-md-inline pl-1">Filter <i class="fas fa-caret-down ml-1"></i></span>
            </button>
            <div class="dropdown-menu dropdown-menu-lg dropdown-filter-menu">
               <form id="form-filter">
                  <div class="p-3">
                     <div class="form-group mb-1">
                        <label for="active-filter">By Active </label>
                        <select class="form-control form-control-sm select-filter" id="active-filter">
                           <option value="">All</option>
                           <option value="0">Yes</option>
                           <option value="1">No</option>
                        </select>
                     </div>
                  </div>
                  <div class="dropdown-divider"></div>
                  <div class="d-flex flex-row-reverse pt-2 pb-2 pl-3 pr-3">
                     <div><button class="btn btn-sm btn-orange ml-1" id="btn_apply"> <span>Apply</span> </button></div>
                     <div><a class="btn btn-sm btn-link text-secondary" id="btn_clear"> <span>Clear</span> </a></div>
                     <div class="mr-auto"><a class="btn btn-sm btn-link text-secondary pl-0" id="close_dropdown"> <span>Close</span> </a></div>
                  </div>
               </form>
            </div>
         </div>
         <div class="col-auto col-lg-3 p-0"> 
            <div class="input-group shadow-sm">
               <input type="search" class="form-control form-control-sm" placeholder="Search" id="search-input">
               <div class="input-group-append">
                 <button class="btn btn-sm btn-outline-secondary" type="button" id="execute-search">
                     <i class="fas fa-sm fa-search"></i>
                  </button>
               </div>
            </div>
         </div>
         <div class="ml-auto">
            {% if perms.config.add_status %}
            <button class="btn btn-xs btn-orange btn-new shadow-sm" id="btn-create-status"><i class="fas fa-xs fa-plus"></i> <span class="d-none d-sm-inline ml-1">Add Status</span></button>
            {% endif %}
         </div>
      </div>

      <!-- Table -->
      <div class="row">
         <div class="col-12 col-sm-12">
            <div class="card shadow-sm mt-2 mb-2">
               <div class="card-body p-0">
                  <template id="table_spinner">
                     <div class="d-flex justify-content-center align-items-center">
                        <div class="spinner-border text-orange mr-2" style="width: 1.2rem; height: 1.2rem;" role="status">
                        </div>
                        <span class="text-secondary">Fetching...</span>
                     </div>
                  </template>
                  <table id="dt_forms" class="table table-hover" width="100%">
                     <thead>
                        <tr>
                           <th>Name</th>
                           <th>Is Active</th>
                        </tr>
                     </thead>
                  </table>
               </div>
            </div>
         </div>
      </div>

   </div>
   <input type="hidden" id="changeStatusHidden" value="{% if perms.config.change_status %}true{% else %}false{% endif %}">

</section>
{% endblock %}

{% block modal %}
<!-- Create -->
<div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-labelledby="formModal" aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content text-sm">
         <div class="modal-header">
            <h6 class="modal-title"></h6>
         </div>
         <div class="modal-body">
            <form id="form">
               <div class="form-group">
                  <!-- Name-->
                  <label>Name <span class="text-danger">*</span></label>
                  <input type="text" class="form-control form-control-sm" id="txt_typename"
                     placeholder="Enter status name">
                  <small class="error-info" id="error-info-status"></small>
               </div>
               <div class="icheck-material-green m-0">
                  <!-- Is Active-->
                  <input type="checkbox" id="chk_status" checked />
                  <label for="chk_status">Is Active</label>
               </div>

            </form>
         </div>
         <div class=" modal-footer">
            <button type="button" class="btn btn-sm btn-light m-0 mr-2" id="btn_cancel" data-dismiss="modal"><span>Cancel</span></button>
            <button type="submit" class="btn btn-sm btn-orange m-0" id="btn_save"><span>Save</span></button>
         </div>
      </div>
   </div>
</div>

{% endblock %}

{% block extrascript %}
<script type="text/javascript" src="{% static 'src/js/config/status.js' %}"></script>
{% endblock %}